### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by mejackreed** [mejackreed/Leaflet-IIIF#46]
- [ ] xhr (see #45)
- [ ] promises

**Comment by epoz** [comment]
I made another attempt at: https://github.com/epoz/Leaflet-IIIF/commit/88fa7ed16f8c145e31ed42afdb1fa5eeb34956d3 using the fetch() API.

@mejackreed comments on Slack:
"Without any arrow function support for Internet Explorer, I think this may be a non-starter until that can come. I would be more inclined to adopting something like the approach in #45 for maximum compatibility."

My goal with this is to use leaflet-iiif in a React app, where I do not want to also load in jQuery just for this one component.

**Comment by abrin** [comment]
would you be more open to pulling out jQuery now that two years have passed? I wonder if the active browser support has rolled along enough that the older browser versions aren't as much of an issue (IE 11 at ~2% according to https://caniuse.com/#feat=arrow-functions)

**Comment by mejackreed** [comment]
@abrin yes. See https://github.com/mejackreed/Leaflet-IIIF/pull/77 for the implementation. I was hoping to get some feedback on that.

**Comment by mejackreed** [comment]
Resolved in #77
