### ISSUE TITLE
Side by side comparison example broken

### ISSUE THREAD

**Issue by DavidHaskiya** [mejackreed/Leaflet-IIIF#61]
Looks like the [side by side example](https://bl.ocks.org/mejackreed/80c4248278517475a30190b427cb5c9c) is broken.

**Comment by mejackreed** [comment]
Thanks for reporting @DavidHaskiya. Looks like Princeton keeps changing their Image API urls. I've updated the example with the new URL. https://gist.github.com/mejackreed/80c4248278517475a30190b427cb5c9c/revisions
