### ISSUE TITLE
Add option for 'setMaxBounds' similar to 'fitBounds'

### ISSUE THREAD

**Issue by dhdemerson** [mejackreed/Leaflet-IIIF#62]
Hello @mejackreed would you be open to a PR that adds an option for `setMaxBounds` that would be similar to `fitBounds`? This option would call Leaflet's [setMaxBounds](http://leafletjs.com/reference-1.0.3.html#map-setmaxbounds) to constrain the viewer to the dimensions of the image.

Really appreciate your work on this, and for keeping it up to date with Leaflet :)

**Comment by mejackreed** [comment]
Yep for sure!
