### ISSUE TITLE
npm version and publish 

### ISSUE THREAD

**Issue by abrin** [mejackreed/Leaflet-IIIF#81]
would it be possible to do a `npm version minor` and npm publish of the repo now that there's a version that doesn't have jQuery? This would enable us to test more easily.

Also, I think we might be able to close this ticket: https://github.com/mejackreed/Leaflet-IIIF/issues/46

**Comment by mejackreed** [comment]
Shipped v3.0.0 https://github.com/mejackreed/Leaflet-IIIF/releases/tag/v3.0.0
